{
  "name": "LuckyCrates",
  "authors": [
    "emilyy-dev"
  ],
  "website": "https://github.com/emilyy-dev/LuckyCrates",
  "version": "${pluginVersion}",
  "main": "io.github.emilyydev.luckycrates.LuckyCratesPlugin",
  "load": "POSTWORLD",
  "depend": [ "Vault" ],

  "permissions": {
    "luckycrates.use": {
      "default": "op",
      "description": "Permission used to allow a player to execute the /luckycrates command",
      "children": {}
    }
  }
}
