name: LuckyCrates
authors: [ Fefo6644 ]
version: ${project.version}
main: me.fefo.luckycrates.LuckyCrates
load: POSTWORLD

permissions:
  luckycrates.use:
    default: op
    description: Permission used to allow a player to execute the /luckycrates command
    children: {}

commands:
  luckycrates:
    aliases: [ lc ]
    permission: luckycrates.use
    permission-message: "§cYou are not allowed to run this command"
    usage: "§cUsages:\n  §c/luckycrates\n  §c/luckycrates nearest\n  §c/luckycrates reload\n  §c/luckycrates remove [nearest]\n  §c/luckycrates (set|setpersistent) <crate type>"
    description: Command used to place and remove spinny crates
